---
- hosts: prod
  tasks:
    - dnf:
        name: httpd
        state: present
        
    - service:
        name: httpd
        state: started
        enabled: yes
        
    - copy:
        src: website1/*
        dest: /var/www/html/
        
    - service:
        name: httpd
        state: restarted
