---
- hosts: prod
  gather_facts: no
  tasks:
    - dnf:
        name: httpd
        state: present

- hosts: 3.109.123.90
  gather_facts: no
  tasks:
    - synchronize:
        src: website1/.
        dest: /var/www/html/
        recursive: yes

- hosts: 13.232.62.115
  gather_facts: no
  tasks:
    - synchronize:
        src: website2/.
        dest: /var/www/html/
        recursive: yes

- hosts: prod
  gather_facts: no
  tasks:
    - service:
        name: httpd
        state: started
        enabled: yes
        
    - service:
        name: httpd
        state: restarted
